
import { Translation } from './types';

export const TRANSLATIONS: Translation = {
  appName: { en: 'Savvy Market', am: 'ሳቪ ገበያ' },
  slogan: { en: 'Savvy is here, everything is here', am: 'ሳቢ ካለ ሁሉም አለ' },
  login: { en: 'Login', am: 'ግባ' },
  register: { en: 'Register', am: 'ተመዝገብ' },
  email: { en: 'Email', am: 'ኢሜይል' },
  emailHint: { en: 'University email recommended', am: 'የዩኒቨርሲቲ ኢሜይል ይመከራል' },
  password: { en: 'Password', am: 'የይለፍ ቃል' },
  fullName: { en: 'Full Name', am: 'ሙሉ ስም' },
  marketplace: { en: 'Marketplace', am: 'ገበያ' },
  dashboard: { en: 'Dashboard', am: 'ዳሽቦርድ' },
  inbox: { en: 'Inbox', am: 'መልእክቶች' },
  admin: { en: 'Admin', am: 'አስተዳዳሪ' },
  logout: { en: 'Logout', am: 'ውጣ' },
  sell: { en: 'Sell', am: 'ሽጥ' },
  search: { en: 'Search products...', am: 'ምርቶችን ፈልግ...' },
  categories: { en: 'Categories', am: 'ምድቦች' },
  all: { en: 'All Items', am: 'ሁሉም' },
  forYou: { en: 'For You', am: 'ለእርስዎ' },
  goods: { en: 'Goods', am: 'ዕቃዎች' },
  course: { en: 'Courses', am: 'ትምህርቶች' },
  academic_materials: { en: 'Academic Materials', am: 'የትምህርት መርጃዎች' },
  food: { en: 'Food & Snacks', am: 'ምግብ እና መክሰስ' },
  noListings: { en: 'No listings available yet. Be the first to post!', am: 'ምንም ዝርዝሮች ገና የሉም። የመጀመሪያው ይሁኑ!' },
  price: { en: 'Price', am: 'ዋጋ' },
  buyNow: { en: 'Buy Now', am: 'አሁን ግዛ' },
  checkout: { en: 'Checkout', am: 'ክፍያ' },
  commission: { en: 'Escrow Fee (5%)', am: 'የመያዣ ክፍያ (5%)' },
  total: { en: 'Total', am: 'ጠቅላላ' },
  feed: { en: 'Feed', am: 'ልጥፎች' },
  myStore: { en: 'My Store', am: 'የኔ ሱቅ' },
  explore: { en: 'Explore.', am: 'ይቃኙ' },
  discoverText: { en: 'Discover the best student-led projects and campus essentials.', am: 'ምርጥ የተማሪ ፕሮጀክቶችን እና ግቢ ውስጥ የሚያስፈልጉ ነገሮችን ያግኙ።' },
  startSelling: { en: 'Start Selling', am: 'መሸጥ ይጀምሩ' },
  chatWithSeller: { en: 'Chat with Seller', am: 'ከሻጩ ጋር ይወያዩ' },
  soldOut: { en: 'Sold Out', am: 'ተሽጦ ያለቀ' },
  availability: { en: 'Availability', am: 'ተገኝነት' },
  inStock: { en: 'in stock', am: 'ክምችት አለ' },
  sellerContact: { en: 'Seller Contact', am: 'የሻጭ አድራሻ' },
  secureCheckout: { en: 'Secure Checkout.', am: 'አስተማማኝ ክፍያ' },
  placeOrder: { en: 'Place Secure Order', am: 'አስተማማኝ ትዕዛዝ ይዘዙ' },
  deliveryInfo: { en: 'Delivery Information', am: 'የማድረሻ መረጃ' },
  deliveryPlaceholder: { en: 'Provide your campus location, dormitory number...', am: 'የግቢዎን ቦታ፣ የዶርም ቁጥር ይጥቀሱ...' },
  revenue: { en: 'Revenue', am: 'ገቢ' },
  activeItems: { en: 'Active Items', am: 'ንቁ ዕቃዎች' },
  unresolved: { en: 'Unresolved', am: 'ያልተፈቱ' },
  commandCenter: { en: 'Command Center.', am: 'መቆጣጠሪያ ማዕከል' },
  inventory: { en: 'Active Inventory', am: 'ንቁ ክምችት' },
  performance: { en: 'Performance', am: 'አፈጻጸም' },
  activityLog: { en: 'Activity Log', am: 'የእንቅስቃሴ መዝገብ' },
  items: { en: 'Items', am: 'ዕቃዎች' },
  orders: { en: 'Orders', am: 'ትዕዛዞች' },
  welcome: { en: 'Welcome to Savvy.', am: 'እንኳን ወደ ሳቪ በሰላም መጡ' },
  exclusiveMarket: { en: 'The exclusive student marketplace.', am: 'ለተማሪዎች ብቻ የተዘጋጀ ገበያ' },
  continue: { en: 'Continue', am: 'ቀጥል' },
  needAccount: { en: 'Need an account?', am: 'መለያ ይፈልጋሉ?' },
  alreadyHaveAccount: { en: 'Already have an account?', am: 'መለያ አለዎት?' },
  pickInterests: { en: 'Pick your interests', am: 'ፍላጎቶችዎን ይምረጡ' },
  finalize: { en: 'Finalize Profile', am: 'መለያዎን ያጠናቅቁ' },
  checkInbox: { en: 'Check your inbox', am: 'ኢሜይልዎን ያረጋግጡ' },
  verificationText: { en: "We've sent a verification link to", am: 'የማረጋገጫ ልከናል ወደ' },
  newListing: { en: 'New Listing.', am: 'አዲስ ሽያጭ' },
  productTitle: { en: 'Product Title', am: 'የምርቱ ስም' },
  description: { en: 'Description', am: 'መግለጫ' },
  contactPhone: { en: 'Contact Phone', am: 'የስልክ ቁጥር' },
  stockCount: { en: 'Stock Count', am: 'የክምችት ብዛት' },
  launchMarket: { en: 'Launch to Market', am: 'ለገበያ አቅርብ' },
  uploadPhoto: { en: 'Upload Photo', am: 'ፎቶ ይጫኑ' },
  category: { en: 'Category', am: 'ምድብ' },
  publishing: { en: 'Publishing...', am: 'በመለጠፍ ላይ...' },
  selectImage: { en: 'Select Image From Device', am: 'ከመሳሪያዎ ምስል ይምረጡ' },
  nextStep: { en: 'Next Step', am: 'ቀጣይ እርምጃ' },
  back: { en: 'Back', am: 'ተመለስ' },
  universityEmail: { en: 'University Email', am: 'የዩኒቨርሲቲ ኢሜይል' },
  createPassword: { en: 'Create Password', am: 'የይለፍ ቃል ፍጠር' },
  min6Chars: { en: 'Min 6 characters', am: 'ቢያንስ 6 ፊደላት' },
  askAnything: { en: 'Ask anything...', am: 'ምንኛውም ነገር ይጠይቁ...' },
  savvyAI: { en: 'Savvy AI Assistant', am: 'የሳቪ AI ረዳት' },
  thinking: { en: 'Thinking...', am: 'በማሰብ ላይ...' },
  landingTitle: { en: 'Campus Commerce, Reimagined.', am: 'የግቢ ግብይት፣ በአዲስ መልክ' },
  landingSubtitle: { en: 'The exclusive student marketplace for Addis Ababa University. Secure, intelligent, and local.', am: 'ለአዲስ አበባ ዩኒቨርሲቲ ተማሪዎች ብቻ የተዘጋጀ ልዩ ገበያ። አስተማማኝ፣ ብልህ እና ቀልጣፋ።' },
  getStarted: { en: 'Get Started', am: 'ይጀምሩ' },
  learnMore: { en: 'Learn More', am: 'ተጨማሪ ይወቁ' },
  whySavvy: { en: 'Why Savvy?', am: 'ለምን ሳቪ?' },
  trustTitle: { en: 'Trust & Safety', am: 'እምነት እና ደህንነት' },
  trustDesc: { en: 'Our escrow system ensures sellers get paid and buyers get what they ordered.', am: 'የእኛ የመያዣ ስርዓት ሻጮች ክፍያቸውን እንዲያገኙ እና ገዢዎች ያዘዙትን ነገር እንዲያገኙ ያረጋግጣል።' },
  aiTitle: { en: 'AI Powered', am: 'በ AI የተደገፈ' },
  aiDesc: { en: 'Our Savvy Assistant helps you price your items and find exactly what you need.', am: 'የእኛ የሳቪ ረዳት የዕቃዎችዎን ዋጋ ለመተመን እና የሚፈልጉትን ነገር በትክክል ለማግኘት ይረዳዎታል።' },
  exclusiveTitle: { en: 'AAU Exclusive', am: 'ለ AAU ብቻ' },
  exclusiveDesc: { en: 'Only verified AAU students can trade, creating a tight-knit and secure community.', am: 'የተረጋገጡ የ AAU ተማሪዎች ብቻ መገበያየት ይችላሉ፣ ይህም አስተማማኝ ማህበረሰብ ይፈጥራል።' },
  platform: { en: 'Platform', am: 'መድረክ' },
  community: { en: 'Community', am: 'ማህበረሰብ' },
  legal: { en: 'Legal', am: 'ህጋዊ' },
  builtForAAU: { en: 'Built for Addis Ababa University Students', am: 'ለአዲስ አበባ ዩኒቨርሲቲ ተማሪዎች የተገነባ' },
};

export const COMMISSION_RATE = 0.05;
export const FIXED_FEE = 10;
