
export const TRANSLATIONS: any = {
  appName: { en: 'Savvy Market', am: 'ሳቪ ገበያ' },
  slogan: { en: 'Savvy is here, everything is here', am: 'ሳቢ ካለ ሁሉም አለ' },
  login: { en: 'Login', am: 'ግባ' },
  register: { en: 'Register', am: 'ተመዝገብ' },
  logout: { en: 'Logout', am: 'ውጣ' },
  email: { en: 'Email', am: 'ኢሜይል' },
  password: { en: 'Password', am: 'የይለፍ ቃል' },
  fullName: { en: 'Full Name', am: 'ሙሉ ስም' },
  marketplace: { en: 'Marketplace', am: 'ገበያ' },
  dashboard: { en: 'Dashboard', am: 'ዳሽቦርድ' },
  sell: { en: 'Sell', am: 'ሽጥ' },
  buyNow: { en: 'Buy Now', am: 'አሁን ግዛ' },
  feed: { en: 'Feed', am: 'ልጥፎች' },
  myStore: { en: 'My Store', am: 'የኔ ሱቅ' },
  startSelling: { en: 'Start Selling', am: 'መሸጥ ይጀምሩ' },
  chatWithSeller: { en: 'Chat with Seller', am: 'ከሻጩ ጋር ይወያዩ' },
  explore: { en: 'Explore.', am: 'ይቃኙ' },
  search: { en: 'Search products...', am: 'ምርቶችን ፈልግ...' },
  exclusiveMarket: { en: 'The exclusive student marketplace.', am: 'ለተማሪዎች ብቻ የተዘጋጀ ገበያ' },
  landingSubtitle: { en: 'The exclusive student marketplace for Addis Ababa University. Secure, intelligent, and local.', am: 'ለአዲስ አበባ ዩኒቨርሲቲ ተማሪዎች ብቻ የተዘጋጀ ልዩ ገበያ። አስተማማኝ፣ ብልህ እና ቀልጣፋ።' },
  getStarted: { en: 'Get Started', am: 'ይጀምሩ' },
  whySavvy: { en: 'Why Savvy?', am: 'ለምን ሳቪ?' },
  trustTitle: { en: 'Trust & Safety', am: 'እምነት እና ደህንነት' },
  trustDesc: { en: 'Our escrow system ensures sellers get paid and buyers get what they ordered.', am: 'የእኛ የመያዣ ስርዓት ሻጮች ክፍያቸውን እንዲያገኙ እና ገዢዎች ያዘዙትን ነገር እንዲያገኙ ያረጋግረጋል።' },
  aiTitle: { en: 'AI Powered', am: 'በ AI የተደገፈ' },
  aiDesc: { en: 'Our Savvy Assistant helps you price your items and find exactly what you need.', am: 'የእኛ የሳቪ ረዳት የዕቃዎችዎን ዋጋ ለመተመን እና የሚፈልጉትን ነገር በትክክል ለማግኘት ይረዳዎታል።' },
  exclusiveTitle: { en: 'AAU Exclusive', am: 'ለ AAU ብቻ' },
  exclusiveDesc: { en: 'Only verified AAU students can trade, creating a tight-knit and secure community.', am: 'የተረጋገጡ የ AAU ተማሪዎች ብቻ መገበያየት ይችላሉ፣ ይህም አስተማማኝ ማህበረሰብ ይፈጥራል።' },
  finalize: { en: 'Finalize Profile', am: 'መለያዎን ያጠናቅቁ' },
  continue: { en: 'Continue', am: 'ቀጥል' },
  pickInterests: { en: 'Pick your interests', am: 'ፍላጎቶችዎን ይምረጡ' },
  all: { en: 'All Items', am: 'ሁሉም' },
  forYou: { en: 'For You', am: 'ለእርስዎ' },
  goods: { en: 'Goods', am: 'ዕቃዎች' },
  course: { en: 'Courses', am: 'ትምህርቶች' },
  academic_materials: { en: 'Academic Materials', am: 'የትምህርት መርጃዎች' },
  food: { en: 'Food & Snacks', am: 'ምግብ እና መክሰስ' },
  price: { en: 'Price', am: 'ዋጋ' },
  revenue: { en: 'Revenue', am: 'ገቢ' },
  activeItems: { en: 'Active Items', am: 'ንቁ ዕቃዎች' },
  unresolved: { en: 'Unresolved', am: 'ያልተፈቱ' },
  commandCenter: { en: 'Command Center.', am: 'መቆጣጠሪያ ማዕከል' },
  items: { en: 'Items', am: 'ዕቃዎች' },
  orders: { en: 'Orders', am: 'ትዕዛዞች' },
  performance: { en: 'Performance', am: 'አፈጻጸም' },
};

export const COMMISSION_RATE = 0.05;
